Repository ttakkeun/Backend_Spring, pull requests merged in 2024-08, with the labels that each got.

#29 [Feat] 사용자 포인트 조회 API 구현
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/GetMyPointResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Point.java
  src/main/java/ttakkeun/ttakkeun_server/repository/PointRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService.java
Labels: :sparkles: feature

#31 [Feat] 사용자 포인트 차감 API 구현
  .github/workflows/dev_deploy.yml
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/ApiResponse.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/UpdateMyPointResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#25 [Feat] 반려동물 프로필 추가 및 조회 기능 구현
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/PetProfileController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/RecordController.java
  src/main/java/ttakkeun/ttakkeun_server/converter/PetProfileConverter.java
  src/main/java/ttakkeun/ttakkeun_server/dto/PetProfileRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/PetProfileResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/RecordListResponse.java
  src/main/java/ttakkeun/ttakkeun_server/dto/RecordListResponseDto.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Pet.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Record.java
  src/main/java/ttakkeun/ttakkeun_server/repository/PetProfileRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/RecordRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetProfileService/PetProfileCommandService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetProfileService/PetProfileCommandServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetProfileService/PetProfileQueryService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetProfileService/PetProfileQueryServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
Labels: :sparkles: feature

#34 [Feat] 진단서 상세 내용 조회 API 구현
  build.gradle
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/GetMyDiagnoseResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/ProductDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Result.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ProductRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ResultRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#41 [Fix] 간단 오류 수정
  src/main/java/ttakkeun/ttakkeun_server/controller/ProductController.java
  src/main/java/ttakkeun/ttakkeun_server/converter/ProductConverter.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistAnswer.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistQuestion.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Member.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Pet.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Product.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Record.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Result.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Todo.java
  src/main/java/ttakkeun/ttakkeun_server/service/LikeService.java
  src/main/java/ttakkeun/ttakkeun_server/service/ProductService.java
Labels: :bug: bug

#46 [Fix] 오류 수정
  src/main/java/ttakkeun/ttakkeun_server/config/SecurityConfig.java
  src/main/java/ttakkeun/ttakkeun_server/controller/PetProfileController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/TodoController.java
Labels: :bug: bug, :recycle: refactor

#38 [Feat] 랭킹, 좋아요 기능 추가 및 코드 리팩토링
  src/main/java/ttakkeun/ttakkeun_server/config/SecurityConfig.java
  src/main/java/ttakkeun/ttakkeun_server/controller/ProductController.java
  src/main/java/ttakkeun/ttakkeun_server/converter/LikeProductConverter.java
  src/main/java/ttakkeun/ttakkeun_server/converter/ProductConverter.java
  src/main/java/ttakkeun/ttakkeun_server/dto/LikeResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/RecommendProductDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/product/ProductApiResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Product.java
  src/main/java/ttakkeun/ttakkeun_server/repository/LikeRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ProductRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ResultRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/custom/CustomLikeRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/custom/CustomLikeRepositoryImpl.java
  src/main/java/ttakkeun/ttakkeun_server/repository/custom/CustomResultRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/custom/CustomResultRepositoryImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/LikeService.java
  src/main/java/ttakkeun/ttakkeun_server/service/ProductService.java
  src/test/java/ttakkeun/ttakkeun_server/ityTest/ProductServiceTest.java
Labels: :sparkles: feature

#55 [Refactor] 엔티티 매핑관계 수정
  src/main/java/ttakkeun/ttakkeun_server/entity/Product.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Result.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ResultProduct.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ProductRepository.java
  src/test/java/ttakkeun/ttakkeun_server/ityTest/ProductServiceTest.java
Labels: :recycle: refactor

#62 [Feat] 진단 결과 네이버 쇼핑 PATCH API 구현
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/NaverProductDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/UpdateProductsRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/UpdateProductsResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Product.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ResultProduct.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ResultProductRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseNaverProductService.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#66 [Feat] 반려동물 프로필 선택 API 구현
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/PetController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/PetProfileController.java
  src/main/java/ttakkeun/ttakkeun_server/converter/PetConverter.java
  src/main/java/ttakkeun/ttakkeun_server/dto/pet/PetRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/pet/PetResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/repository/PetProfileRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/PetRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetProfileService/PetProfileCommandService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetProfileService/PetProfileCommandServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetProfileService/PetProfileQueryService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetCommandService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetCommandServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetQueryService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetQueryServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetService.java
Labels: :sparkles: feature, :recycle: refactor

#70 [Refactor] 엔티티 매핑 변수 이름 수정
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistAnswer.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistQuestion.java
  src/main/java/ttakkeun/ttakkeun_server/entity/History.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Image.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Member.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Pet.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Record.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Result.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Todo.java
  src/main/java/ttakkeun/ttakkeun_server/repository/PetRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/RecordRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ResultRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/TodoRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/CompletionRateService.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
  src/main/java/ttakkeun/ttakkeun_server/service/TodoService.java
Labels: :recycle: refactor

#71 [Feat] 일지 관련 API 구현
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/RecordController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/record/RecordRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/record/RecordResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistQuestion.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Record.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ChecklistAnswerRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ChecklistQuestionRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
Labels: :sparkles: feature

#73 [Feat] 진단 결과 목록 조회 API 구현
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseTestController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/DiagnoseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/GetMyDiagnoseListResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Record.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Result.java
  src/main/java/ttakkeun/ttakkeun_server/repository/PetRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ResultRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService.java
Labels: :sparkles: feature

#74 [Refactor] 포인트 조회, 포인트 차감 API 에러처리 수정
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseTestController.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService.java
Labels: :recycle: refactor

#77 [Feat] 일지 관련 API 구현
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/RecordController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/record/RecordResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/repository/RecordRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
Labels: :sparkles: feature

#85 [Refactor] ChecklistAnswer 엔티티 추가
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistAnswer.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistQuestion.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Image.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Record.java
  src/main/java/ttakkeun/ttakkeun_server/entity/UserAnswer.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ChecklistAnswerRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/UserAnswerRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
Labels: :recycle: refactor

#91 [Feat] 반려동물 프로필 수정 API 구현 및 어노테이션 추가
  src/main/java/ttakkeun/ttakkeun_server/controller/PetController.java
  src/main/java/ttakkeun/ttakkeun_server/converter/PetConverter.java
  src/main/java/ttakkeun/ttakkeun_server/dto/pet/PetResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Pet.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetCommandService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetCommandServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetQueryService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetQueryServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetService.java
Labels: :sparkles: feature

#92 [Refactor] api 응답방식 변경 및 어노테이션 추가
  src/main/java/ttakkeun/ttakkeun_server/controller/ProductController.java
  src/main/java/ttakkeun/ttakkeun_server/converter/ProductConverter.java
  src/main/java/ttakkeun/ttakkeun_server/repository/ProductRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/LikeService.java
  src/main/java/ttakkeun/ttakkeun_server/service/ProductService.java
Labels: :recycle: refactor

#94 [Feat]일지 사진 추가 테스트 성공
  src/main/java/ttakkeun/ttakkeun_server/config/SecurityConfig.java
  src/main/java/ttakkeun/ttakkeun_server/controller/RecordController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/record/RecordRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetService.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
  src/main/java/ttakkeun/ttakkeun_server/service/S3ImageService.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#95 [Feat] 일지 관련 API 수정
  src/main/java/ttakkeun/ttakkeun_server/controller/RecordController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/record/RecordRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/record/RecordResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistAnswer.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistQuestion.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Record.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
Labels: :sparkles: feature

#97 [Feat] UserAnswer 엔티티 수정 및 API 수정
  src/main/java/ttakkeun/ttakkeun_server/converter/StringListConverter.java
  src/main/java/ttakkeun/ttakkeun_server/entity/ChecklistQuestion.java
  src/main/java/ttakkeun/ttakkeun_server/entity/UserAnswer.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
Labels: :sparkles: feature

#99 [Feat] 일지 상세 내용 조회 API 응답 수정
  src/main/java/ttakkeun/ttakkeun_server/dto/record/RecordResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/service/RecordService.java
Labels: :sparkles: feature

#109 [Refactor] 임의의 멤버 객체 삭제
  src/main/java/ttakkeun/ttakkeun_server/controller/RecordController.java
Labels: :recycle: refactor

#113 [Feat] AI진단하기 API 구현
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/config/ChatGPTConfig.java
  src/main/java/ttakkeun/ttakkeun_server/config/SecurityConfig.java
  src/main/java/ttakkeun/ttakkeun_server/controller/ChatGPTTestController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/DiagnoseTestController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/RecordController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/ChatGPTCompletionDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/ChatGPTQuestionDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/ChatGPTRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/PostDiagnoseRequestDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/PostDiagnoseResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/entity/UserAnswer.java
  src/main/java/ttakkeun/ttakkeun_server/repository/RecordRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService/DiagnoseChatGPTService.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService/DiagnoseNaverProductService.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService/DiagnoseService.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService/UseChatGPTService.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#117 [Feat] 투두 관련 API 수정
  src/main/java/ttakkeun/ttakkeun_server/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/ttakkeun/ttakkeun_server/controller/TodoController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/todo/CalendarResponseDto.java
  src/main/java/ttakkeun/ttakkeun_server/dto/todo/ChangeDateRequestDto.java
  src/main/java/ttakkeun/ttakkeun_server/dto/todo/RepeatAnotherDayRequestDto.java
  src/main/java/ttakkeun/ttakkeun_server/dto/todo/TodoResponseDto.java
  src/main/java/ttakkeun/ttakkeun_server/dto/todo/TodoStatusUpdateRequestDto.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Todo.java
  src/main/java/ttakkeun/ttakkeun_server/repository/TodoRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/CalendarService.java
  src/main/java/ttakkeun/ttakkeun_server/service/TodoService.java
Labels: :sparkles: feature

#119 [Fix] 진단 PATCH API 에러 수정
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService/DiagnoseNaverProductService.java
Labels: :bug: bug

#120 [Refactor] 진단 PATCH API 필터링 추가
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService/DiagnoseNaverProductService.java
Labels: :recycle: refactor

#123 [Test] CI/CD 조건 변경 여부 확인용
  src/main/java/ttakkeun/ttakkeun_server/config/SecurityConfig.java
  src/main/java/ttakkeun/ttakkeun_server/controller/TestController.java
Labels: :construction_worker: ci

#124 [Test] CI/CD 조건 변경 여부 확인용
  src/main/java/ttakkeun/ttakkeun_server/controller/TestController.java
Labels: :construction_worker: ci

#122 [Feat] todo 및 tips 수정
  src/main/java/ttakkeun/ttakkeun_server/controller/CalendarController.java
  src/main/java/ttakkeun/ttakkeun_server/controller/TipController.java
  src/main/java/ttakkeun/ttakkeun_server/dto/tip/TipResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/dto/todo/TodoDto.java
  src/main/java/ttakkeun/ttakkeun_server/dto/todo/TodoResponseDto.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Member.java
  src/main/java/ttakkeun/ttakkeun_server/entity/Tip.java
  src/main/java/ttakkeun/ttakkeun_server/repository/LikeTipRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/TipRepository.java
  src/main/java/ttakkeun/ttakkeun_server/repository/TodoRepository.java
  src/main/java/ttakkeun/ttakkeun_server/service/CalendarService.java
  src/main/java/ttakkeun/ttakkeun_server/service/TipService.java
  src/main/java/ttakkeun/ttakkeun_server/service/TodoService.java
Labels: :sparkles: feature

#128 [Refactor] PetService 통합
  src/main/java/ttakkeun/ttakkeun_server/controller/PetController.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetCommandService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetCommandServiceImpl.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetQueryService.java
  src/main/java/ttakkeun/ttakkeun_server/service/PetService/PetQueryServiceImpl.java
Labels: :recycle: refactor

#130 [Refactor] AI진단 API response값 수정
  src/main/java/ttakkeun/ttakkeun_server/dto/diagnose/PostDiagnoseResponseDTO.java
  src/main/java/ttakkeun/ttakkeun_server/service/DiagnoseService/DiagnoseChatGPTService.java
Labels: :recycle: refactor
